const RESPONSE_OK = 'OK';

const VIEWS = {
  DIALOG_FANGWU_INFO: 'DIALOG_FANGWU_INFO',
  DIALOG_ZHANGHU_INFO: 'DIALOG_ZHANGHU_INFO',

  JIAOCUN_GOUFANGREN: 'JIAOCUN_GOUFANGREN',
  JIAOCUN_GOUFANGREN_DIALOG_JIAOKUAN : 'JIAOCUN_GOUFANGREN_DIALOG_JIAOKUAN',
  JIAOCUN_GOUFANGREN_DIALOG_TUIKUAN: 'JIAOCUN_GOUFANGREN_DIALOG_TUIKUAN',

  JIAOCUN_WEIBEIAN: 'JIAOCUN_WEIBEIAN',
  JIAOCUN_WEIBEIAN_DIALOG_JIAOCUN: 'JIAOCUN_WEIBEIAN_DIALOG_JIAOCUN',

  JIAOCUN_TUIKUAN: 'JIAOCUN_TUIKUAN',

  JIAOCUN_PIAOJU: 'JIAOCUN_PIAOJU',
  JIAOCUN_PIAOJU_DIALOG_ZHIKUANDAN: 'JIAOCUN_PIAOJU_DIALOG_ZHIKUANDAN',
  JIAOCUN_PIAOJU_DIALOG_TONGJI: 'JIAOCUN_PIAOJU_DIALOG_TONGJI',
  JIAOCUN_PIAOJU_DIALOG_LINGQU : 'JIAOCUN_PIAOJU_DIALOG_LINGQU',
  JIAOCUN_PIAOJU_DIALOG_LINGQU_SEARCH: 'JIAOCUN_PIAOJU_DIALOG_LINGQU_SEARCH',
  JIAOCUN_PIAOJU_DIALOG_PRINT_BOFU : 'JIAOCUN_PIAOJU_DIALOG_PRINT_BOFU',
  JIAOCUN_PIAOJU_DIALOG_PRINT_TUIKUAN: 'JIAOCUN_PIAOJU_DIALOG_PRINT_TUIKUAN',

}

const JIGOU = {
  KAIFA   : 0,
  FUWU    : 1,
  YEZHU   : 2 ,
  // SHENJIE,
  // SHIGONG,
  // GONGYOU,
}

const LOUDONG_JZJG = {
  GANGHUN: 0,
  HUNHE: 1,
  KUANGJIA: 2,
  KUANGJIAN: 3,
  MUJIEGOU: 4,
  QITA: 5,
}

const FANGWU_YONGTU = {
  ZHUZHAI : 0,
  SHANGYE : 1,
  BANGONG : 2,
  CHEKU   : 3,
  CHEWEI  : 4
}

const FANGWU_LEIXING = {
  ZHUZHAI_YOUDIANTI         : 0,
  ZHUZHAI_WUDIANTI          : 1,
  SHANGWUYONGFANG_YOUDIANTI :2,
  SHANGWUYONGFANG_WUDIANTI  :3,
  BANGONGYONGFANG_YOUDIANTI :4,
  BANGONGYONGFANG_WUDIANTI  :5,
  GONGYEYONGFANG_YOUDIANTI  :6,
  GONGYEYONGFANG_WUDIANTI   :7,
  CANGCHUYONGFANG_YOUDIANTI :8,
  CANGCHUYONGFANG_WUDIANTI  :9,
  CHEKU_YOUDIANTI           :10,
  CHEKU_WUDIANTI            :11,
  QITA_YOUDIANTI            :12,
  QITA_WUDIANTI             :13,
  YISHOUGONGFANG_YOUDIANTI  :14,
  YISHOUGONGFANG_WUDIANTI   :15,
}

const TUIKUAN_YUANYIN = {
  TUIKUAN: 0,
}

export default {
  VIEWS,
  RESPONSE_OK,
  JIGOU,
  LOUDONG_JZJG,
  FANGWU_YONGTU,
  FANGWU_LEIXING,
  TUIKUAN_YUANYIN,
}

